name: 'Deploy on push'

on:
  push:
    branches:
      - master

jobs:
  forge-deploy:
    name: 'Laravel Forge Deploy'
    runs-on: ubuntu-latest

    steps:
      # Trigger Laravel Forge Deploy
      - name: Deploy
        uses: jbrooksuk/laravel-forge-action@v1.0.2
        with:
          trigger_url: https://forge.laravel.com/servers/556062/sites/2296172/deploy/http?token=MGdtmfAnPsia458cKzX51s1fuHAod1LXrWlv1blU
